import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import db from "@/server/db/drizzle";
import { categories } from "@/server/db/schema";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const result = await db.select().from(categories)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <nav className="flex bg-slate-200 gap-10 px-8">
            <Link href="/">
              Home
            </Link>
            <Link href="/create-product">
              Create Product
            </Link>
            {result.map(({name}) => (
              <Link key={name} href={`/?category=${name}`}>
                {name}
              </Link>
            ))}
          </nav>
          <div className="p-8">
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
